### ISSUE TITLE
Unable to send message to agent ERROR

### ISSUE THREAD

**Issue by sa-cloud** [skydive-project/skydive#1925]
I use helm to install the skydive latest version on an k8s cluster v1.13 with the configuration below:

image:
    repository: cognetive/skydive
    tag: latest
env:
    # For debug purposes
    - name: SKYDIVE_LOGGING_LEVEL
      value: "INFO"

    # ANALYZER_STARTUP_CAPTURE_GREMLIN invoke at startup capturing in selected nodes
    - name: SKYDIVE_ANALYZER_STARTUP_CAPTURE_GREMLIN
      value: "G.V().has('Name', NE('lo'))"

    - name: SKYDIVE_ANALYZER_STARTUP_CAPTURE_BPF
      value: "not (tcp dst port 8082 or tcp dst port 9000)"

    - name: SKYDIVEX_AGENT_CAPTURE_SYN
      value: "True"

    # DEFAULT_LAYER_KEY_MODE - the layers used to identify a unique flow.
    - name: SKYDIVE_FLOW_DEFAULT_LAYER_KEY_MODE
      value: "L3"

    - name: SKYDIVE_ANALYZER_STARTUP_CAPTURE_TYPE
      value: "pcap"

    - name: SKYDIVE_AGENT_CAPTURE_SYN
      value: "True"

I get analyzer log full of errors:
ERROR   client/client.go:145 (*OnDemandClient).registerTask     kube-dal12-cr0c27d3069b054b24a3fd7a44bde5aecc-w3.cloud.ibm: Unable to send message to agent : No result found
ERROR   client/client.go:145 (*OnDemandClient).registerTask     kube-dal12-cr0c27d3069b054b24a3fd7a44bde5aecc-w3.cloud.ibm: Unable to send message to agent kube-dal12-cr0c27d3069b054b24a3fd7a44bde5aecc-w3.cloud.ibm: No result found

**Comment by hunchback** [comment]
@lebauce - note that `cognetive/skydive:latest` is the same as `skydive/skydive:latest`.

**Comment by safchain** [comment]
Is there any other error before ? can you send a full log ?

**Comment by sa-cloud** [comment]
[logs-from-skydive-analyzer-in-sa-collect-ibm-skydive-dev-analyzer-6d757c6d-zrzxq.txt](https://github.com/skydive-project/skydive/files/3445559/logs-from-skydive-analyzer-in-sa-collect-ibm-skydive-dev-analyzer-6d757c6d-zrzxq.txt)

**Comment by sa-cloud** [comment]
[logs-from-skydive-agent-in-sa-collect-ibm-skydive-dev-agent-lb5lb.txt](https://github.com/skydive-project/skydive/files/3445575/logs-from-skydive-agent-in-sa-collect-ibm-skydive-dev-agent-lb5lb.txt)

**Comment by sa-cloud** [comment]
skydive-agent
Image:
cognetive/skydive:latest
Environment variables:
SKYDIVE_ANALYZERS: sa-collect-ibm-skydive-dev-service:8082
SKYDIVE_FLOW_PROTOCOL: websocket
SKYDIVE_FLOW_DEFAULT_LAYER_KEY_MODE: L3
SKYDIVE_AGENT_TOPOLOTY_PROBS: ovsdb docker runc
SKYDIVE_AGENT_TOPOLOGY_RUNC_RUN_PATH: /var/run/runc /var/run/runc-ctrs /var/run/containerd/runc
SKYDIVE_LOGGING_LEVEL: INFO
SKYDIVE_ANALYZER_STARTUP_CAPTURE_GREMLIN: G.V().has('Name', NE('lo'))
SKYDIVE_ANALYZER_STARTUP_CAPTURE_BPF: not (tcp dst port 8082 or tcp dst port 9000)
SKYDIVEX_AGENT_CAPTURE_SYN: True
SKYDIVE_FLOW_DEFAULT_LAYER_KEY_MODE: L3
SKYDIVE_ANALYZER_STARTUP_CAPTURE_TYPE: pcap
SKYDIVE_AGENT_CAPTURE_SYN: True

**Comment by sa-cloud** [comment]
skydive-analyzer
Image:
cognetive/skydive:latest
Environment variables:
SKYDIVE_UI: {"theme":"light","k8s_enabled":"true","topology": {"favorites":{"infrastructure":"G.V().Has(\"Manager\",NE(\"k8s\"))","kubernetes":"G.V().Has(\"Manager\",\"k8s\")"},"default_filter":"infrastructure"}}
SKYDIVE_ANALYZER_TOPOLOGY_PROBES: k8s
SKYDIVE_EMBEDDED: true
SKYDIVE_FLOW_PROTOCOL: websocket
SKYDIVE_LOGGING_LEVEL: INFO
SKYDIVE_ANALYZER_STARTUP_CAPTURE_GREMLIN: G.V().has('Name', NE('lo'))
SKYDIVE_ANALYZER_STARTUP_CAPTURE_BPF: not (tcp dst port 8082 or tcp dst port 9000)
SKYDIVEX_AGENT_CAPTURE_SYN: True
SKYDIVE_FLOW_DEFAULT_LAYER_KEY_MODE: L3
SKYDIVE_ANALYZER_STARTUP_CAPTURE_TYPE: pcap
SKYDIVE_AGENT_CAPTURE_SYN: True

**Comment by safchain** [comment]
@sa-cloud thanks for providing logs, I'll have a look

**Comment by safchain** [comment]
@sa-cloud The errors are not critical. It basically because you have a capture definition that matches even nodes that are not interface. We are about the submit a fix in order to remove these errors messages.

**Comment by safchain** [comment]
Addressed by #1938

**Comment by hunchback** [comment]
@sa-cloud / @dubek - please confirm that #1938 fixes the reported issue

**Comment by hunchback** [comment]
closing: will @sa-cloud please re-open if needed

**Comment by sa-cloud** [comment]
In 2019.09.02___08.41 I still see the errors:

2019-09-02T11:22:35.015Z	INFO	analyzer/analyzer.go:42 glob..func1	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Skydive Analyzer _2019-09-02T05:45:19 starting...
2019-09-02 11:22:35.016268 I | embed: listening for peers on http://127.0.0.1:12380 
2019-09-02 11:22:35.016527 I | embed: listening for client requests on 127.0.0.1:12379
2019-09-02 11:22:35.019048 I | etcdserver: name = kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm
2019-09-02 11:22:35.019074 I | etcdserver: data dir = /var/lib/skydive/etcd
2019-09-02 11:22:35.019083 I | etcdserver: member dir = /var/lib/skydive/etcd/member
2019-09-02 11:22:35.019090 I | etcdserver: heartbeat = 100ms
2019-09-02 11:22:35.019096 I | etcdserver: election = 1000ms
2019-09-02 11:22:35.019102 I | etcdserver: snapshot count = 100000
2019-09-02 11:22:35.019115 I | etcdserver: advertise client URLs = http://127.0.0.1:12379 
2019-09-02 11:22:35.019124 I | etcdserver: initial advertise peer URLs = http://localhost:12380 
2019-09-02 11:22:35.019136 I | etcdserver: initial cluster = kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm=http://localhost:12380 
2019-09-02 11:22:35.026660 I | etcdserver: starting member c9ac9fc89eae9cf7 in cluster f290f7f84a022555
2019-09-02 11:22:35.026744 I | raft: c9ac9fc89eae9cf7 became follower at term 0
2019-09-02 11:22:35.026764 I | raft: newRaft c9ac9fc89eae9cf7 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2019-09-02 11:22:35.026772 I | raft: c9ac9fc89eae9cf7 became follower at term 1
2019-09-02 11:22:35.034020 W | auth: simple token is not cryptographically signed
2019-09-02 11:22:35.060799 I | etcdserver: starting server... [version: 3.2.15+git, cluster version: to_be_decided]
2019-09-02 11:22:35.064465 I | etcdserver/membership: added member c9ac9fc89eae9cf7 [http://localhost:12380 ] to cluster f290f7f84a022555
2019-09-02 11:22:35.927106 I | raft: c9ac9fc89eae9cf7 is starting a new election at term 1
2019-09-02 11:22:35.927217 I | raft: c9ac9fc89eae9cf7 became candidate at term 2
2019-09-02 11:22:35.927245 I | raft: c9ac9fc89eae9cf7 received MsgVoteResp from c9ac9fc89eae9cf7 at term 2
2019-09-02 11:22:35.927264 I | raft: c9ac9fc89eae9cf7 became leader at term 2
2019-09-02 11:22:35.927297 I | raft: raft.node: c9ac9fc89eae9cf7 elected leader c9ac9fc89eae9cf7 at term 2
2019-09-02 11:22:35.927661 I | etcdserver: setting up the initial cluster version to 3.2
2019-09-02 11:22:35.929398 I | etcdserver: published {Name:kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm ClientURLs:[http://127.0.0.1:12379 ]} to cluster f290f7f84a022555
2019-09-02 11:22:35.929436 I | embed: ready to serve client requests
2019-09-02 11:22:35.929542 I | Server is ready!
2019-09-02 11:22:35.929779 N | embed: serving insecure client requests on 127.0.0.1:12379, this is strongly discouraged!
2019-09-02 11:22:35.931251 N | etcdserver/membership: set the initial cluster version to 3.2
2019-09-02 11:22:35.931313 I | etcdserver/api: enabled capabilities for version 3.2
2019-09-02T11:22:35.936Z	INFO	analyzer/storage.go:61 newGraphBackendFromConfig	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Using memory (driver memory) as graph storage backend
2019-09-02T11:22:35.937Z	INFO	analyzer/storage.go:116 newFlowBackendFromConfig	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Using memory (driver memory) as flow storage backend
2019-09-02T11:22:35.945Z	INFO	k8s/probe.go:155 NewProbe	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Probe k8s subprobes [deployment daemonset configmap networkpolicy persistentvolume job cluster node secret cronjob replicationcontroller pod ingress namespace endpoints statefulset storageclass persistentvolumeclaim container service replicaset]
2019-09-02T11:22:36.060Z	INFO	analyzer/server.go:127 (*Server).createStartupCapture	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Invoke capturing of type pcap from startup with gremlin: G.V().has('Name', NE('lo')) and BPF: not (tcp dst port 8082 or tcp dst port 9000)
2019-09-02T11:22:36.118Z	INFO	http/server.go:104 (*Server).Listen	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Listening on socket 0.0.0.0:8082
2019-09-02T11:22:36.128Z	INFO	etcd/election.go:102 (*MasterElector).start	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: starting as the master for /master-analyzer-ondemand-client-Capture: kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm
2019-09-02T11:22:36.130Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:36.132Z	INFO	etcd/election.go:102 (*MasterElector).start	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: starting as the master for /master-analyzer-ondemand-client-PacketInjection: kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm
2019-09-02T11:22:36.135Z	INFO	etcd/election.go:102 (*MasterElector).start	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: starting as the master for /master-analyzer-alert-server: kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm
2019-09-02T11:22:36.138Z	INFO	etcd/election.go:102 (*MasterElector).start	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: starting as the master for /master-analyzer-topology-manager: kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm
2019-09-02T11:22:36.142Z	INFO	analyzer/analyzer.go:55 glob..func1	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Skydive Analyzer started !
2019-09-02T11:22:36.999Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:38.001Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:39.007Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:39.998Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:40.998Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:41.998Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:42.999Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:43.999Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:44.999Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:46.017Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:46.998Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:47.998Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:48.998Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:49.998Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:51.001Z	ERROR	client/client.go:145 (*OnDemandClient).registerTask	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Unable to send message to agent kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: No result found
2019-09-02T11:22:51.371Z	INFO	websocket/server.go:117 (*Server).newIncomingClient	kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: New WebSocket Connection from 10.149.8.213:15967 : URI path /ws/subscriber/flow
