### ISSUE TITLE
skydive panic: runtime error: index out of range

### ISSUE THREAD

**Issue by whl739** [skydive-project/skydive#2195]
I used the latested version of binary, and it crashed when i start an agent. My config is :
```
analyzers:
- 10.254.84.82:8082

logging:
  level: DEBUG

agent:
  topology:
    probes:
      - lldp
```

And the output is:
```
2020-03-26T23:34:13.954+0800    INFO    agent/agent.go:41 glob..func1   test-host-2 Skydive Agent 0.26.0-bdb15fd05031 starting...
2020-03-26T23:34:13.954+0800    WARN    agent/agent.go:114 NewAgent     test-host-2: Agent needs root permissions for some feature like capture, network namespace introspection, some feature might not work as expected
2020-03-26T23:34:13.954+0800    DEBUG   websocket/pool.go:109 (*Pool).AddClient test-host-2: AddClient test-host-2 for pool HubClientPool type : [*websocket.Pool]
2020-03-26T23:34:13.955+0800    INFO    plugin/topology.go:47 LoadTopologyPlugins       test-host-2: Topology plugins: []
2020-03-26T23:34:13.955+0800    INFO    agent/topology_probes.go:148 NewTopologyProbeBundle     test-host-2: Topology probes: [hardware netlink netns lldp]
2020-03-26T23:34:13.955+0800    INFO    agent/flow_probes.go:42 NewFlowProbeBundle      test-host-2: Flow probes: [pcapsocket ovssflow sflow gopacket dpdk ebpf ovsmirror ovsnetflow]
2020-03-26T23:34:13.955+0800    ERROR   agent/flow_probes.go:84 NewFlowProbeBundle      test-host-2: Failed to create ovssflow probe: ovssflow probe depends on ovsdb topology probe, probe can't start properly
2020-03-26T23:34:13.955+0800    INFO    agent/flow_probes.go:86 NewFlowProbeBundle      test-host-2: Not compiled with dpdk support, skipping it
2020-03-26T23:34:13.955+0800    ERROR   agent/flow_probes.go:84 NewFlowProbeBundle      test-host-2: Failed to create ovsmirror probe: ovsmirror probe depends on ovsdb topology probe, probe can't start properly
2020-03-26T23:34:13.955+0800    ERROR   agent/flow_probes.go:84 NewFlowProbeBundle     test-host-2: Failed to create ovsnetflow probe: ovsnetflow probe depends on ovsdb topology probe, probe can't start properly
2020-03-26T23:34:13.955+0800    INFO    http/server.go:105 (*Server).Listen     test-host-2: Listening on socket 127.0.0.1:8081
2020-03-26T23:34:13.955+0800    INFO    websocket/client.go:528 (*Client).Connect       test-host-2: Connecting to ws://10.254.84.82:8082/ws/agent/topology
2020-03-26T23:34:13.956+0800    DEBUG   netns/netns.go:291 (*ProbeHandler).start        test-host-2: ProbeHandler initialized
2020-03-26T23:34:13.958+0800    INFO    websocket/client.go:552 (*Client).Connect       test-host-2: Connected to ws://10.254.84.82:8082/ws/agent/topology
2020-03-26T23:34:13.958+0800    INFO    common/forwarder.go:55 (*Forwarder).OnNewMaster test-host-2: Using 10.254.84.82:8082 as master of topology forwarder
2020-03-26T23:34:13.997+0800    INFO    agent/agent.go:51 glob..func1   test-host-2: Skydive Agent started
2020-03-26T23:34:13.997+0800    INFO    common/forwarder.go:36 (*Forwarder).triggerResync       test-host-2: Start a re-sync
2020-03-26T23:34:13.998+0800    DEBUG   client/flow_client.go:80 (*FlowClientUDPConn).Connect   test-host-2: UDP client dialup done for 10.254.84.82:8082
2020-03-26T23:34:14.097+0800    DEBUG   netlink/netlink.go:1089 (*Probe).start  test-host-2: Start polling netlink event for e4703d00-6945-434b-5497-75b056055875
2020-03-26T23:34:14.097+0800    DEBUG   netlink/netlink.go:836 (*Probe).initialize      test-host-2: Initialize Netlink interfaces for e4703d00-6945-434b-5497-75b056055875
panic: runtime error: index out of range

goroutine 230 [running]:
github.com/vishvananda/netlink.parseIptunData(0x3f51c00, 0xc000616140, 0xc000788c00, 0xd, 0x10)
        /var/lib/jenkins/workspace/skydive-create-binaries/pkg/mod/github.com/lebauce/netlink@v0.0.0-20190122103356-fa328be7c8d2/link_linux.go:2324 +0x2bd
github.com/vishvananda/netlink.LinkDeserialize(0x0, 0xc00036d28c, 0x590, 0xac0, 0x3f51c00, 0xc000616000, 0x0, 0x0)
        /var/lib/jenkins/workspace/skydive-create-binaries/pkg/mod/github.com/lebauce/netlink@v0.0.0-20190122103356-fa328be7c8d2/link_linux.go:1480 +0xd7a
github.com/vishvananda/netlink.(*Handle).LinkList(0xc0005606e0, 0x3b4067c, 0x24, 0xc0002327d0, 0x1, 0x1)
        /var/lib/jenkins/workspace/skydive-create-binaries/pkg/mod/github.com/lebauce/netlink@v0.0.0-20190122103356-fa328be7c8d2/link_linux.go:1608 +0x2f9
github.com/skydive-project/skydive/topology/probes/netlink.(*Probe).initialize(0xc0009de0c0)
        /var/lib/jenkins/workspace/skydive-create-binaries/src/github.com/skydive-project/skydive/topology/probes/netlink/netlink.go:837 +0xf0
github.com/skydive-project/skydive/topology/probes/netlink.(*Probe).start(0xc0009de0c0, 0xc0005dc680)
        /var/lib/jenkins/workspace/skydive-create-binaries/src/github.com/skydive-project/skydive/topology/probes/netlink/netlink.go:1096 +0x227
created by github.com/skydive-project/skydive/topology/probes/netlink.(*ProbeHandler).Register
        /var/lib/jenkins/workspace/skydive-create-binaries/src/github.com/skydive-project/skydive/topology/probes/netlink/netlink.go:1282 +0x2d2
```

On the other server, agent works fine, configuration is same. The differences are nic interfaces and network env.
The normal side is:
```
$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP mode DEFAULT group default qlen 1000
    link/ether xx brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP mode DEFAULT group default qlen 1000
    link/ether xx brd ff:ff:ff:ff:ff:ff
5: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether xx brd ff:ff:ff:ff:ff:ff
```

The crashed side is:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether xx brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 xdp qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether xx brd ff:ff:ff:ff:ff:ff
```
Compared with the nomal side, it is not bonding, eth0 is offline, and eth1 has a xdp program.

**Comment by lebauce** [comment]
I just pushed a PR for the library we use to talk to netlink and an other one on Skydive to include the fix : https://github.com/skydive-project/skydive/pull/2196
Could you please give it a try ? Thanks !

**Comment by whl739** [comment]
go build got an error:
```
go: github.com/lebauce/netlink@v0.0.0-20200327154308-f4921fca5803: invalid pseudo-version: does not match version-control timestamp (2020-03-27T20:26:35Z)
```

**Comment by whl739** [comment]
I modified `go.mod`, and it could be compiled.
```
github.com/vishvananda/netlink v1.0.0 => github.com/lebauce/netlink f4921fca5803
```
After test, it works fine.

**Comment by whl739** [comment]
I got another panic:
```
panic: interface conversion: interface {} is nil, not string

goroutine 293 [running]:
github.com/skydive-project/skydive/topology/enhancers.(*TopologyManager).nodeID(...)
        /home/work/skydive/topology/enhancers/topology_manager.go:133
github.com/skydive-project/skydive/topology/enhancers.(*TopologyManager).createNode(0xc000101900, 0xc000c74840, 0xc000d29af0, 0x6)
        /home/work/skydive/topology/enhancers/topology_manager.go:137 +0x3ba
github.com/skydive-project/skydive/topology/enhancers.(*TopologyManager).handleCreateNode(0xc000101900, 0xc000c74840, 0x0, 0x0)
        /home/work/skydive/topology/enhancers/topology_manager.go:182 +0x155
github.com/skydive-project/skydive/topology/enhancers.(*TopologyManager).syncTopology(0xc000101900)
        /home/work/skydive/topology/enhancers/topology_manager.go:92 +0xcc
github.com/skydive-project/skydive/topology/enhancers.(*TopologyManager).OnNodeAdded(0xc000101900, 0xc00019d830)
        /home/work/skydive/topology/enhancers/topology_manager.go:270 +0x2b
github.com/skydive-project/skydive/graffiti/graph.(*EventHandler).notifyListeners(0xc0003d3a40, 0x2, 0x4e35340, 0xc00019d830, 0x0, 0x0)
        /home/work/skydive/graffiti/graph/graph.go:253 +0x17b
github.com/skydive-project/skydive/graffiti/graph.(*EventHandler).NotifyEvent(0xc0003d3a40, 0x2, 0x4e35340, 0xc00019d830)
        /home/work/skydive/graffiti/graph/graph.go:286 +0x150
github.com/skydive-project/skydive/graffiti/graph.(*Graph).AddNode(0xc0003d16e0, 0xc00019d830, 0x0, 0xc000b52f60)
        /home/work/skydive/graffiti/graph/graph.go:1098 +0x96
github.com/skydive-project/skydive/graffiti/graph.(*Graph).NewNode(0xc0003d16e0, 0xc000b1ce10, 0x24, 0xc000b52f60, 0xc000c2cd48, 0x1, 0x1, 0x0, 0xc0003a2e00, 0xc0004538c0)
        /home/work/skydive/graffiti/graph/graph.go:1152 +0x1a8
github.com/skydive-project/skydive/topology/enhancers.(*TopologyManager).createNode(0xc000101900, 0xc000c6dec0, 0xc000d295d0, 0x6)
        /home/work/skydive/topology/enhancers/topology_manager.go:149 +0x2d6
github.com/skydive-project/skydive/topology/enhancers.(*TopologyManager).handleCreateNode(0xc000101900, 0xc000c6dec0, 0x0, 0x186)
        /home/work/skydive/topology/enhancers/topology_manager.go:182 +0x155
github.com/skydive-project/skydive/topology/enhancers.(*TopologyManager).handleNodeRuleRequest(0xc000101900, 0xc000d29548, 0x3, 0x562b7a0, 0xc000c6dec0, 0x5, 0x185)
        /home/work/skydive/topology/enhancers/topology_manager.go:214 +0x7a
github.com/skydive-project/skydive/topology/enhancers.(*TopologyManager).onAPIWatcherEvent(0xc000101900, 0xc000d29548, 0x3, 0xc000b1cd8a, 0x24, 0x562b7a0, 0xc000c6dec0)
        /home/work/skydive/topology/enhancers/topology_manager.go:258 +0x8c
github.com/skydive-project/skydive/graffiti/api/rest.(*BasicAPIHandler).AsyncWatch.func1(0xc000c1e6c0, 0x5560740, 0xc000bb4e00, 0xc000c0e860, 0xa, 0xc000214e70, 0xc000bb1300)
        /home/work/skydive/graffiti/api/rest/kv.go:196 +0x285
created by github.com/skydive-project/skydive/graffiti/api/rest.(*BasicAPIHandler).AsyncWatch
        /home/work/skydive/graffiti/api/rest/kv.go:165 +0x34c
```

It crashed when i use python api, and the meta data didn't contain `Type` and `Name`:
```
func (tm *TopologyManager) nodeID(node *types.NodeRule) graph.Identifier {
    return graph.GenID(node.Metadata["Type"].(string), node.Metadata["Name"].(string))
}
```
But when i add `Type` and `Name`, it still crashed. Below is my code:
```
from skydive.rest.client import RESTClient

restclient = RESTClient("localhost:8082")
meta = {}
meta["Name"] = "test-1"
meta["Type"] = "host"
restclient.noderule_create("create", meta)
```

**Comment by lebauce** [comment]
@whl739 I just pushed a PR that tries to fix the last issue you faced : https://github.com/skydive-project/skydive/pull/2200 Could you please give it a try ? Thanks !

**Comment by whl739** [comment]
I tested this PR, it returned `skydive.rest.client.BadRequest: Invalid schema` if i didn't set the right schema.
